project_name: aci-monitor
env_files:
  github_token: ~/.github.com.token
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - rm -rf dist
    - go mod download
    - go test
builds:
  -
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archives:
  -
    format: zip
    replacements:
      darwin: MacOS
      windows: Windows
      linux: Linux
      amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
